name: Daily Commit

on:
  schedule:
    # Runs every day at a random minute between 0-59 of 0 UTC
    - cron: '0 12 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Make a dummy commit
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'actions@github.com'
          # Create an empty commit with timestamp in message
          git commit --allow-empty -m "chore: daily commit $(date -u)"
          git push
